contents:
  repositories:
    - https://dl-cdn.alpinelinux.org/alpine/edge/main
    - '@local /github/workspace/packages'
  packages:
    - alpine-baselayout-data
    - nginx@local

entrypoint:
  type: service-bundle
  services:
    nginx: /usr/sbin/nginx -c /etc/nginx/nginx.conf -g "daemon off;"

accounts:
  groups:
    - groupname: nginx
      gid: 10000
  users:
    - username: nginx
      uid: 10000
